spec:
  project: default
  source:
    repoURL: https://github.com/Omarovskyi/FinalStepProject.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

ingress-nginx:
  controller:
    ingressClassResource:
      enabled: false 
    service:
      type: LoadBalancer